# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('module_id', models.IntegerField(null=True)),
                ('api_name', models.CharField(max_length=20, null=True)),
                ('api_protocol', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.TextField(null=True)),
                ('param_type', models.CharField(max_length=20, null=True)),
                ('api_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.TextField(null=True)),
                ('case_desc', models.TextField(null=True)),
                ('pro_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
                ('depnd_api_id', models.IntegerField(null=True)),
                ('case_protocol', models.CharField(max_length=5, null=True)),
                ('case_url', models.TextField(null=True)),
                ('case_method', models.TextField(null=True)),
                ('input_data', models.TextField(null=True)),
                ('exp_status', models.IntegerField(null=True)),
                ('exp_header', models.TextField(null=True)),
                ('exp_data', models.TextField(null=True)),
                ('check_id', models.IntegerField(null=True)),
                ('param_type', models.CharField(max_length=20, null=True)),
                ('case_schema', models.TextField(null=True)),
                ('is_run_sql', models.IntegerField(null=True)),
                ('front_sql', models.TextField(null=True)),
                ('rear_sql', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSuite',
            fields=[
                ('case_suite_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
                ('case_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('check_name', models.CharField(max_length=20, null=True)),
                ('check_code', models.TextField(null=True)),
                ('check_desc', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepndApi',
            fields=[
                ('depnd_api_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('depnd_api_name', models.CharField(max_length=20, null=True)),
                ('depnd_api_protocol', models.CharField(max_length=10, null=True)),
                ('depnd_api_method', models.CharField(max_length=10, null=True)),
                ('depnd_api_url', models.CharField(max_length=50, null=True)),
                ('depnd_api_type', models.CharField(max_length=20, null=True)),
                ('depnd_api_desc', models.TextField(null=True)),
                ('depnd_api_param', models.TextField(null=True)),
                ('depnd_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('env_name', models.CharField(max_length=20, null=True)),
                ('env_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('func_name', models.CharField(max_length=30, null=True)),
                ('func_code', models.TextField(null=True)),
                ('func_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('module_name', models.CharField(max_length=20, null=True)),
                ('module_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
                ('pass_num', models.IntegerField(null=True)),
                ('fail_num', models.IntegerField(null=True)),
                ('unrun_num', models.IntegerField(null=True)),
                ('start_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
                ('report_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('result_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField(null=True)),
                ('case_id', models.IntegerField(null=True)),
                ('api_id', models.IntegerField(null=True)),
                ('input_data', models.TextField(null=True)),
                ('out_data', models.TextField(null=True)),
                ('is_pass', models.IntegerField(null=True)),
                ('status_check', models.IntegerField(null=True)),
                ('header_check', models.IntegerField(null=True)),
                ('schema_check', models.IntegerField(null=True)),
                ('schema_msg', models.TextField(null=True)),
                ('body_check', models.IntegerField(null=True)),
                ('err_msg', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('plan_name', models.TextField(null=True)),
                ('plan_type', models.IntegerField(null=True)),
                ('plan_interval', models.IntegerField(null=True)),
                ('start_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
                ('env_id', models.IntegerField(null=True)),
                ('suite_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('suite_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('suite_name', models.CharField(max_length=20, null=True)),
                ('suite_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('var_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField(null=True)),
                ('var_name', models.CharField(max_length=20, null=True)),
                ('var_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField(null=True)),
                ('var_id', models.IntegerField(null=True)),
                ('env_id', models.IntegerField(null=True)),
                ('var_value', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
